### ISSUE TITLE
Hide Frame type from user

### ISSUE THREAD

**Issue by Asalle** [roc-project/roc-go#2]
Hiding `Frame` type, i.e. replacing it with `frame`, and replacing `Sender.Write(*Frame)` with type-safe wrappers like `Sender.WriteAudioBytes([]byte)` and `Sender.WriteAudioFloats([]float)`, as described in roc-project/roc#248.

Exporting something like this to the user:
```
type Frame struct {
	Samples       unsafe.Pointer
	SamplesSize   uint
}
```
would be too low-level and unfamiliar for a Go library (because of the unsafe.Pointer).

**Comment by Asalle** [comment]
I don't know any way to unexport one particular type in `c-for-go`. I suggest we add this feature to it. If the matter is urgent, we can create a `sed` command in makefile.

https://github.com/xlab/c-for-go/issues/85

**Comment by gavv** [comment]
See https://github.com/roc-project/roc-go/pull/14#issuecomment-565834039

Actually it was straightforward: https://github.com/roc-project/roc-go/blob/054e8b9e1c88312c406960c19652c29e0fafb217/roc.yml#L58

**Comment by gavv** [comment]
(I've unexported the frame type and removed Receiver.Read and Sender.Write. Now we have to add type-safe wrappers instead of them).

**Comment by Asalle** [comment]
Haha, okay :D
Thanks!

**Comment by Asalle** [comment]
this issue can be closed?

**Comment by gavv** [comment]
No, because of my last comment: https://github.com/roc-project/roc-go/issues/2#issuecomment-565835042

**Comment by Asalle** [comment]
ok

**Comment by Asalle** [comment]
Closing this, as we moved on to hand-written bindings and can control the visibility of types
