### ISSUE TITLE
Implement Logger

### ISSUE THREAD

**Issue by Asalle** [roc-project/roc-go#5]
Hm, it seems that LogSetHandlerImpl generated by c-for-go already stores the function into a global variable:

roc-go/roc/cgo_helpers.go
Lines 682 to 690 in 251b447
```
 func (x LogHandler) PassValue() (ref C.roc_log_handler, allocs *cgoAllocMap) { 
 	if x == nil { 
 		return nil, nil 
 	} 
 	if logHandler9E4BBC5EFunc == nil { 
 		logHandler9E4BBC5EFunc = x 
 	} 
 	return (C.roc_log_handler)(C.roc_log_handler_9e4bbc5e), nil 
 } 
```
So we don't need to duplicate this code.

However, it also seems that the generated code is not thread-safe. We should learn whether c-for-go is capable of generating thread-safe code. If it's not, we should implement thread-safety in our wrappers. The goal is to make the entire API thread-safe, just like original C API.

**Comment by gavv** [comment]
So there are two things to remember:

* don't forget to add log level to logger message
* don't forget to make the logger function thread-safe
