### ISSUE TITLE
Don't modify generated code

### ISSUE THREAD

**Issue by gavv** [roc-project/roc-go#7]
We should never modify generated code by hand. Otherwise our edits would be lost after regeneration. But we should be able to regenerate code when needed, e.g. when a new libroc release is out.

See https://github.com/roc-project/roc-go/pull/1#discussion_r344453767

**Comment by Asalle** [comment]
I think this is done, I removed all hand-fixed things from generated code in #14 
So if we merge it we can mark this as done?

**Comment by gavv** [comment]
Great.

> So if we merge it we can mark this as done?

Yes.
