### ISSUE TITLE
Reduce allocations on hot path

### ISSUE THREAD

**Issue by gavv** [roc-project/roc-go#8]
We should try to avoid allocations when writing and reading frames.

If the user gives us a []float slice, we can get the pointer to the raw memory of the slice data (using unsafe I guess) and pass this pointer to roc_sender_write().

Theoretically this should work because roc_sender_write() does not store this pointer anywhere. It is guaranteed that this memory will not be accessed after the function returns, so this approach should not cause problems with GC (these problems are the reason why cgo uses C.calloc which I'd like to avoid).

See https://github.com/roc-project/roc-go/pull/1#issuecomment-546422861

**Comment by gavv** [comment]
cc @Asalle

**Comment by Asalle** [comment]
Closing this, as we moved on to hand-written bindings
